[package]
name = "codec-h264"
description = "h264 codec utilities"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
byteorder = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
tracing = { workspace = true }
bitstream-io = { workspace = true }
num = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

utils = { workspace = true }
codec-bitstream = { workspace = true }
