[package]
name = "stream-center"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
lazy_static = "1.5.0"
serde_json = "1.0.133"
thiserror = "2.0.7"
tokio = "1.42.0"
tokio-util = "0.7.13"
tracing = "0.1.41"
