[package]
name = "stream-center"
description = "media stream publish and subscribe center"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
dashmap = "6.1.0"
lazy_static = "1.5.0"
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
bitstream-io = { workspace = true }
num = { workspace = true }
uuid = { workspace = true, features = ["v7", "fast-rng", "macro-diagnostics"] }

amf-formats = { workspace = true }
flv-formats = { workspace = true }
rtp-formats = { workspace = true }
utils = { workspace = true }
codec-common = { workspace = true }
codec-h264 = { workspace = true }
codec-aac = { workspace = true }
codec-bitstream = { workspace = true }

debug-tools = { path = "../debug_tools" }
