[package]
name = "yams"
description = "yet another media server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "app_utils"
path = "src/lib.rs"

[[bin]]
name = "yam_server"
path = "src/media_server.rs"

[[bin]]
name = "stun_client"
path = "src/stun_client.rs"

[[bin]]
name = "stun_server"
path = "src/stun_server.rs"

[[bin]]
name = "turn_server"
path = "src/turn_server.rs"

[workspace]
members = [
    ".",
    "codec/*",
    "formats/*",
    "servers/*",
    "unifiedio",
    "connection",
    "utils",
    "streamcenter",
    "debug_tools",
    "yam_server",
    "stun_client",
    "stun_server",
    "turn_server",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["zhuwenq <zhuwenqa@outlook.com>"]
repository = "https://github.com/leonezz/media-server"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full", "tracing"] }
tokio-util = { version = "0.7.17", features = ["full"] }
console-subscriber = "0.5.0"
tracing = "0.1.44"
clap = { version = "4.5.53", features = [
    "derive",
    "string",
    "cargo",
    "env",
    "unicode",
    "wrap_help",
] }
figment = { version = "0.10.19", features = ["yaml", "json", "toml"] }
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
byteorder = "1.5.0"
bitstream-io = "4.9.0"
num = "0.4.3"
uuid = "1.19.0"
either = "1.15.0"
ring = "0.17.14"
itertools = "0.14.0"
futures = "0.3.31"
base64 = "0.22.1"
url = "2.5.7"
chrono = "0.4.40"
inventory = "0.3.21"
rootcause = { version = "0.11.0" }
function_name = "0.3.0"

codec-aac = { path = "codec/aac" }
codec-bitstream = { path = "codec/bitstream" }
codec-common = { path = "codec/common" }
codec-h264 = { path = "codec/h264" }

debug-tools = { path = "debug_tools" }

amf-formats = { path = "formats/amf" }
flv-formats = { path = "formats/flv" }
rtmp-formats = { path = "formats/rtmp" }
rtp-formats = { path = "formats/rtp" }
rtsp-formats = { path = "formats/rtsp" }
sdp-formats = { path = "formats/sdp" }
stun-formats = { path = "formats/stun" }
webrtc-formats = { path = "formats/webrtc" }
iana-formats = { path = "formats/iana" }
turn-formats = { path = "formats/turn" }

http-server = { path = "servers/http" }
rtmp-server = { path = "servers/rtmp" }
rtp-session = { path = "servers/rtp" }
rtsp-server = { path = "servers/rtsp" }
stun-server = { path = "servers/stun" }
turn-server = { path = "servers/turn" }
server-utils = { path = "servers/utils" }

unified-io = { path = "unifiedio" }
connection = { path = "connection" }

utils = { path = "utils" }

stream-center = { path = "streamcenter" }

[dependencies]
tracing-subscriber = { version = "0.3.22", features = [
    "time",
    "local-time",
    "fmt",
    "std",
    "env-filter",
] }
thiserror = { workspace = true }
tokio = { workspace = true }
console-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
time = { version = "0.3.44", features = ["macros"] }
tracing-appender = { version = "0.2.4" }
serde = { workspace = true }
iana-formats = { workspace = true, features = ["serde"] }
utils = { workspace = true }
rootcause = { workspace = true }
function_name = { workspace = true }

yam_server = { path = "yam_server" }
stun_client = { path = "stun_client" }
stun_server = { path = "stun_server" }
# turn_server = { path = "turn_server" }

[profile.dev]
incremental = true
