[package]
name = "rtsp-server"
description = "server and session for rtsp publish and play"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
futures = { workspace = true }
tracing = { workspace = true }
num = { workspace = true }
uuid = { workspace = true, features = ["v7", "fast-rng", "macro-diagnostics"] }
url = { workspace = true }
chrono = { workspace = true }
scopeguard = "1.1"

unified-io = { workspace = true }
rtsp-formats = { workspace = true }
sdp-formats = { workspace = true }
rtp-session = { workspace = true }
rtp-formats = { workspace = true }
utils = { workspace = true }
server-utils = { workspace = true }
codec-h264 = { workspace = true }
codec-aac = { workspace = true }
codec-common = { workspace = true }
stream-center = { workspace = true }

debug-tools = { workspace = true }


[lints.clippy]
uninlined_format_args = "allow"
