[package]
name = "http-server"
description = "server session for http-flv/webrtc/rest api endpoints"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
byteorder = { workspace = true }
num = { workspace = true }
axum = "0.8.4"
futures = { workspace = true }
tokio-stream = "0.1.17"
figment = { version = "0.10", features = ["env", "toml", "json"] }
base64 = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v7", "fast-rng", "macro-diagnostics"] }

utils = { workspace = true }
stream-center = { workspace = true }
flv-formats = { workspace = true }
sdp-formats = { workspace = true }
webrtc-formats = { workspace = true }
codec-common = { workspace = true }
server-utils = { workspace = true }

[dev-dependencies]
debug-tools = { workspace = true }