[package]
name = "yam_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.42.0"
rtmp-formats = { path = "../formats/rtmp" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-tracy = "0.11.3"

[[bin]]
name = "yam_server"
path = "main.rs"
