[package]
name = "amf-formats"
description = "encoder and decoder for amf0 and amf3 formats"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
byteorder = { workspace = true }
either = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }

utils = { workspace = true }
