[package]
name = "rtmp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
rtmp-formats = { path = "../../formats/rtmp" }
thiserror = "2.0.6"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }

tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-tracy = "0.11.3"
tracing-futures = { version = "0.2.5", features = ["tokio"] }
