[package]
name = "rtmp-server"
description = "server and session for rtmp publish and play endpoints"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
rtmp-formats = { workspace = true }
amf-formats = { workspace = true }
flv-formats = { workspace = true }
utils = { workspace = true }
codec-common = { workspace = true }
codec-h264 = { workspace = true }
stream-center = { workspace = true }
unified-io = { workspace = true }
server-utils = { workspace = true }

thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true }
tracing = { workspace = true }
num = { workspace = true }
uuid = { workspace = true, features = ["v7", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
debug-tools = { workspace = true }
