[package]
name = "stun-server"
description = "agent and client and server for STUN protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
futures = { workspace = true }

stun-formats = { workspace = true }
utils = { workspace = true }
connection = { workspace = true }
