[package]
name = "connection"
description = "unified socket level connection"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
tokio = { workspace = true, features = ["net", "time"] }
tokio-util = { workspace = true, features = ["full"] }
socket2 = "0.6.1"
tracing = { workspace = true }
futures = { workspace = true }
utils = { workspace = true }
iana-formats = { workspace = true }

pin-project = "1"
