[package]
name = "codec-bitstream"
description = "bitstream utilities for codec utilities"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
byteorder = { workspace = true }
tracing = { workspace = true }
bitstream-io = { workspace = true }
num = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

utils = { workspace = true }
