[package]
name = "utils"
description = "common utilities"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.9.1"
rand_core = "0.9.3"
bitstream-io = { workspace = true }
ring = { workspace = true }
md5 = "0.8.0"
crc = "3.3.0"
tokio-util = { workspace = true }
clap = { workspace = true }
figment = { workspace = true, features = ["yaml"] }
serde = { workspace = true }
serde_ini = "0.2.0"
iana-formats = { workspace = true }
