[package]
name = "sdp-formats"
description = "encoder and decoder for sdp formats"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
itertools = { workspace = true }

utils = { workspace = true }
