[package]
name = "rtp-formats"
description = "encoder and decoder for rtp protocol formats"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
byteorder = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
tracing = { workspace = true }
num = { workspace = true }
utils = { workspace = true }
codec-h264 = { workspace = true }
codec-aac = { workspace = true }
codec-bitstream = { workspace = true }
codec-common = { workspace = true }
itertools = { workspace = true }
bitstream-io = { workspace = true }
futures = { workspace = true }
unified-io = { workspace = true }
base64 = { workspace = true }
sdp-formats = { workspace = true }
