[package]
name = "rtp-session"
description = "server and session for rtp/rtcp send and receive"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
futures = { workspace = true }
tracing = { workspace = true }
num = { workspace = true }
uuid = { workspace = true, features = ["v7", "fast-rng", "macro-diagnostics"] }

rtp-formats = { workspace = true }
unified-io = { workspace = true }
utils = { workspace = true }
