[package]
name = "rtmp-formats"
description = "encoder and decoder for rtmp protocol message formats"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { workspace = true }
byteorder = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
tracing = { workspace = true }
num = { workspace = true }

amf-formats = { workspace = true }
utils = { workspace = true }
