[package]
name = "rtmp"
version = "0.1.0"
edition = "2024"

[dependencies]
amf = { path = "../amf" }
byteorder = "1.5.0"
hmac = "0.12.1"
rand = "0.8.5"
rand_core = "0.6.4"
sha2 = "0.10.8"
thiserror = "2.0.3"
tokio = "1.42.0"
tokio-util = { version = "0.7.12", features = ["full"] }
