[package]
name = "aac"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
thiserror = "2.0.7"
bitstream-io = "2.6.0"
tokio-util = { version = "0.7.13", features = ["full"] }
utils = { path = "../../utils" }
