[package]
name = "yam_server"
description = "yet another media server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true }
thiserror = { workspace = true }

rtmp-server = { workspace = true }
http-server = { workspace = true }
rtsp-server = { workspace = true }
stream-center = { workspace = true }
iana-formats = { workspace = true }
utils = { workspace = true }
